/**
 * Documentation pages read from the imported tree.
 *
 * GENERATED by scripts/import-docs.ts. Edit the import, not this file.
 */

import type { DocsCategory, Locale } from '@poppy/project-data';

export interface ImportedDocPage {
  route: string;
  slug: string;
  category: DocsCategory;
  title: string;
  description: string;
  locale: Locale;
}

export const importedDocs: Record<string, ImportedDocPage[]> = {
  "ori": [
    {
      "route": "/ori/docs/development/bootstrapping/",
      "slug": "bootstrapping",
      "category": "development",
      "title": "Bootstrapping",
      "description": "Como compilar o Ori a partir do código-fonte.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/development/report-bugs/",
      "slug": "report-bugs",
      "category": "development",
      "title": "Como reportar bugs",
      "description": "O que incluir num relato de bug para que ele possa ser reproduzido.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/getting-started/first-project/",
      "slug": "first-project",
      "category": "guides",
      "title": "Primeiro projeto e pacotes locais",
      "description": "Como criar um projeto, declarar pacotes locais e compilar um primeiro programa.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/getting-started/install/",
      "slug": "install",
      "category": "guides",
      "title": "Instalação",
      "description": "Como instalar o Ori, conferir a instalação com ori doctor e atualizar para uma nova versão.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/getting-started/tour/",
      "slug": "tour",
      "category": "guides",
      "title": "Tour da linguagem",
      "description": "Um passeio pela superfície S3: módulos, funções, tipos, result, match, pipe e traits.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/language/advanced/",
      "slug": "advanced",
      "category": "guides",
      "title": "Recursos avançados",
      "description": "Slices, contratos, genéricos const, atributos de declaração, SIMD, arenas de memória e destrutores.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/language/concurrency/",
      "slug": "concurrency",
      "category": "guides",
      "title": "Async e concorrência",
      "description": "async e await, tasks, canais, atômicos e tokens de cancelamento.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/language/interop/",
      "slug": "interop",
      "category": "guides",
      "title": "Interop e ABI C",
      "description": "Como chamar C com extern e publicar funções Ori para C com @c_export.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/manual/cookbook/",
      "slug": "cookbook",
      "category": "guides",
      "title": "Cookbook",
      "description": "Receitas para projetos pequenos e médios, com código S3 válido.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/manual/debugging/",
      "slug": "debugging",
      "category": "guides",
      "title": "Depuração",
      "description": "O depurador de terminal, o servidor DAP e a integração com editores.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/manual/errors-null-void/",
      "slug": "errors-null-void",
      "category": "guides",
      "title": "Erros, optional e void",
      "description": "O modelo mental de ausência e falha: optional, result, try e void.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/manual/performance/",
      "slug": "performance",
      "category": "guides",
      "title": "Desempenho",
      "description": "Microbench comparando Ori, Python e Rust, com o método usado.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/manual/testing/",
      "slug": "testing",
      "category": "guides",
      "title": "Testes",
      "description": "Como testar programas Ori com @test e ori test, e como testar o compilador.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/reference/cli-reference/",
      "slug": "cli-reference",
      "category": "guides",
      "title": "Referência da CLI",
      "description": "Todos os comandos da CLI ori, suas opções e variáveis de ambiente.",
      "locale": "pt-BR"
    },
    {
      "route": "/ori/docs/guides/reference/stdlib-reference/",
      "slug": "stdlib-reference",
      "category": "guides",
      "title": "Mapa da biblioteca padrão",
      "description": "Os módulos ori.X da biblioteca padrão, posições de texto e convenções de erro.",
      "locale": "pt-BR"
    },
    {
      "route": "/en/ori/docs/development/bootstrapping/",
      "slug": "bootstrapping",
      "category": "development",
      "title": "Bootstrapping",
      "description": "How to build Ori from source.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/development/report-bugs/",
      "slug": "report-bugs",
      "category": "development",
      "title": "How to report bugs",
      "description": "What to include in a bug report so it can be reproduced.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/getting-started/first-project/",
      "slug": "first-project",
      "category": "guides",
      "title": "First project and local packages",
      "description": "How to create a project, declare local packages, and compile a first program.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/getting-started/install/",
      "slug": "install",
      "category": "guides",
      "title": "Installing Ori",
      "description": "How to install Ori, check the install with ori doctor, and upgrade to a new release.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/getting-started/tour/",
      "slug": "tour",
      "category": "guides",
      "title": "Language tour",
      "description": "A walk through the S3 surface: modules, functions, types, result, match, pipe, and traits.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/language/advanced/",
      "slug": "advanced",
      "category": "guides",
      "title": "Advanced features",
      "description": "Slices, contracts, const generics, declaration attributes, SIMD, memory arenas, and destructors.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/language/concurrency/",
      "slug": "concurrency",
      "category": "guides",
      "title": "Async and concurrency",
      "description": "async and await, tasks, channels, atomics, and cancellation tokens.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/language/interop/",
      "slug": "interop",
      "category": "guides",
      "title": "Interop and the C ABI",
      "description": "How to call C with extern and publish Ori functions to C with @c_export.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/manual/cookbook/",
      "slug": "cookbook",
      "category": "guides",
      "title": "Cookbook",
      "description": "Recipes for small and medium projects, in valid S3 code.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/manual/debugging/",
      "slug": "debugging",
      "category": "guides",
      "title": "Debugging",
      "description": "The terminal debugger, the DAP server, and editor integration.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/manual/errors-null-void/",
      "slug": "errors-null-void",
      "category": "guides",
      "title": "Errors, optional, and void",
      "description": "The mental model of absence and failure: optional, result, try, and void.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/manual/performance/",
      "slug": "performance",
      "category": "guides",
      "title": "Performance",
      "description": "A microbenchmark comparing Ori, Python, and Rust, with the method used.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/manual/testing/",
      "slug": "testing",
      "category": "guides",
      "title": "Testing",
      "description": "How to test Ori programs with @test and ori test, and how to test the compiler.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/reference/cli-reference/",
      "slug": "cli-reference",
      "category": "guides",
      "title": "CLI reference",
      "description": "Every ori CLI command, its options, and environment variables.",
      "locale": "en"
    },
    {
      "route": "/en/ori/docs/guides/reference/stdlib-reference/",
      "slug": "stdlib-reference",
      "category": "guides",
      "title": "Standard library map",
      "description": "The ori.X standard library modules, text positions, and error conventions.",
      "locale": "en"
    }
  ],
  "aipo": [
    {
      "route": "/aipo/docs/development/adp/ADP-001-byte-and-core-types-as-values/",
      "slug": "ADP-001-byte-and-core-types-as-values",
      "category": "development",
      "title": "ADP 001 Byte And Core Types As Values",
      "description": "Aipo — ADP 001 Byte And Core Types As Values",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/adp/ADP-002-construction-hooks-and-runtime-contracts/",
      "slug": "ADP-002-construction-hooks-and-runtime-contracts",
      "category": "development",
      "title": "ADP 002 Construction Hooks And Runtime Contracts",
      "description": "Aipo — ADP 002 Construction Hooks And Runtime Contracts",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/adp/ADP-003-execution-budgets/",
      "slug": "ADP-003-execution-budgets",
      "category": "development",
      "title": "ADP 003 Execution Budgets",
      "description": "Aipo — ADP 003 Execution Budgets",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/adp/ADP-004-unicode-identifier-policy/",
      "slug": "ADP-004-unicode-identifier-policy",
      "category": "development",
      "title": "ADP 004 Unicode Identifier Policy",
      "description": "Aipo — ADP 004 Unicode Identifier Policy",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/adp/ADP-005-parser-recursion-bounds/",
      "slug": "ADP-005-parser-recursion-bounds",
      "category": "development",
      "title": "ADP 005 Parser Recursion Bounds",
      "description": "Aipo — ADP 005 Parser Recursion Bounds",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/adp/ADP-006-wave3-wave4-open-decisions/",
      "slug": "ADP-006-wave3-wave4-open-decisions",
      "category": "development",
      "title": "ADP 006 Wave3 Wave4 Open Decisions",
      "description": "Aipo — ADP 006 Wave3 Wave4 Open Decisions",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/adp/ADP-007-package-identity-and-distribution/",
      "slug": "ADP-007-package-identity-and-distribution",
      "category": "development",
      "title": "ADP 007 Package Identity And Distribution",
      "description": "Aipo — ADP 007 Package Identity And Distribution",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/adp/ADP-008-v0.1.0-language-release/",
      "slug": "ADP-008-v0.1.0-language-release",
      "category": "development",
      "title": "ADP 008 V0.1.0 Language Release",
      "description": "Aipo — ADP 008 V0.1.0 Language Release",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/adp/ADP-009-synchronous-c-abi/",
      "slug": "ADP-009-synchronous-c-abi",
      "category": "development",
      "title": "ADP 009 Synchronous C Abi",
      "description": "Aipo — ADP 009 Synchronous C Abi",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/adp/ADP-010-interoperability-thin-proofs/",
      "slug": "ADP-010-interoperability-thin-proofs",
      "category": "development",
      "title": "ADP 010 Interoperability Thin Proofs",
      "description": "Aipo — ADP 010 Interoperability Thin Proofs",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/adp/ADP-011-performance-and-ergonomics-roadmap/",
      "slug": "ADP-011-performance-and-ergonomics-roadmap",
      "category": "development",
      "title": "ADP 011 Performance And Ergonomics Roadmap",
      "description": "Aipo — ADP 011 Performance And Ergonomics Roadmap",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/architecture/adr/001-architecture-baseline/",
      "slug": "001-architecture-baseline",
      "category": "development",
      "title": "001 Architecture Baseline",
      "description": "Aipo — 001 Architecture Baseline",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/architecture/bytecode-and-vm/",
      "slug": "bytecode-and-vm",
      "category": "development",
      "title": "Bytecode And Vm",
      "description": "Aipo — Bytecode And Vm",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/architecture/clean-code-contract/",
      "slug": "clean-code-contract",
      "category": "development",
      "title": "Clean Code Contract",
      "description": "Aipo — Clean Code Contract",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/architecture/compiler-frontend/",
      "slug": "compiler-frontend",
      "category": "development",
      "title": "Compiler Frontend",
      "description": "Aipo — Compiler Frontend",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/architecture/crates/",
      "slug": "crates",
      "category": "development",
      "title": "Crates",
      "description": "Aipo — Crates",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/architecture/host-abi/",
      "slug": "host-abi",
      "category": "development",
      "title": "Host Abi",
      "description": "Aipo — Host Abi",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/architecture/js-emitter/",
      "slug": "js-emitter",
      "category": "development",
      "title": "Js Emitter",
      "description": "Aipo — Js Emitter",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/architecture/overview/",
      "slug": "overview",
      "category": "development",
      "title": "Overview",
      "description": "Aipo — Overview",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-001/",
      "slug": "adp-001",
      "category": "development",
      "title": "Adp 001",
      "description": "Aipo — Adp 001",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-002/",
      "slug": "adp-002",
      "category": "development",
      "title": "Adp 002",
      "description": "Aipo — Adp 002",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-003/",
      "slug": "adp-003",
      "category": "development",
      "title": "Adp 003",
      "description": "Aipo — Adp 003",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-004/",
      "slug": "adp-004",
      "category": "development",
      "title": "Adp 004",
      "description": "Aipo — Adp 004",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-005/",
      "slug": "adp-005",
      "category": "development",
      "title": "Adp 005",
      "description": "Aipo — Adp 005",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-006/",
      "slug": "adp-006",
      "category": "development",
      "title": "Adp 006",
      "description": "Aipo — Adp 006",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-007/",
      "slug": "adp-007",
      "category": "development",
      "title": "Adp 007",
      "description": "Aipo — Adp 007",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-008/",
      "slug": "adp-008",
      "category": "development",
      "title": "Adp 008",
      "description": "Aipo — Adp 008",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-009/",
      "slug": "adp-009",
      "category": "development",
      "title": "Adp 009",
      "description": "Aipo — Adp 009",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-010/",
      "slug": "adp-010",
      "category": "development",
      "title": "Adp 010",
      "description": "Aipo — Adp 010",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-011/",
      "slug": "adp-011",
      "category": "development",
      "title": "Adp 011",
      "description": "Aipo — Adp 011",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-012/",
      "slug": "adp-012",
      "category": "development",
      "title": "Adp 012",
      "description": "Aipo — Adp 012",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/decisions/adp-013/",
      "slug": "adp-013",
      "category": "development",
      "title": "Adp 013",
      "description": "Aipo — Adp 013",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/design/zoe-visual-modernization-dossier/",
      "slug": "zoe-visual-modernization-dossier",
      "category": "development",
      "title": "Zoe Visual Modernization Dossier",
      "description": "Aipo — Zoe Visual Modernization Dossier",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P00-G09-slice-s9/",
      "slug": "P00-G09-slice-s9",
      "category": "development",
      "title": "P00 G09 Slice S9",
      "description": "Aipo — P00 G09 Slice S9",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P00-G10-backend-completion/",
      "slug": "P00-G10-backend-completion",
      "category": "development",
      "title": "P00 G10 Backend Completion",
      "description": "Aipo — P00 G10 Backend Completion",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P00-G11-cli-and-formatter/",
      "slug": "P00-G11-cli-and-formatter",
      "category": "development",
      "title": "P00 G11 Cli And Formatter",
      "description": "Aipo — P00 G11 Cli And Formatter",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P00-G12-conformance-and-mvp-gate/",
      "slug": "P00-G12-conformance-and-mvp-gate",
      "category": "development",
      "title": "P00 G12 Conformance And Mvp Gate",
      "description": "Aipo — P00 G12 Conformance And Mvp Gate",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P00-G13-construction-hooks-and-bytes/",
      "slug": "P00-G13-construction-hooks-and-bytes",
      "category": "development",
      "title": "P00 G13 Construction Hooks And Bytes",
      "description": "Aipo — P00 G13 Construction Hooks And Bytes",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P00-G14-runtime-contract-enforcement/",
      "slug": "P00-G14-runtime-contract-enforcement",
      "category": "development",
      "title": "P00 G14 Runtime Contract Enforcement",
      "description": "Aipo — P00 G14 Runtime Contract Enforcement",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P00-G15-static-contracts-and-interface-conformance/",
      "slug": "P00-G15-static-contracts-and-interface-conformance",
      "category": "development",
      "title": "P00 G15 Static Contracts And Interface Conformance",
      "description": "Aipo — P00 G15 Static Contracts And Interface Conformance",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P00-G16-wave-1-exit-review/",
      "slug": "P00-G16-wave-1-exit-review",
      "category": "development",
      "title": "P00 G16 Wave 1 Exit Review",
      "description": "Aipo — P00 G16 Wave 1 Exit Review",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P01-G01-js-parity-mvp-subset/",
      "slug": "P01-G01-js-parity-mvp-subset",
      "category": "development",
      "title": "P01 G01 Js Parity Mvp Subset",
      "description": "Aipo — P01 G01 Js Parity Mvp Subset",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P01-G02-deep-quality-gauntlet/",
      "slug": "P01-G02-deep-quality-gauntlet",
      "category": "development",
      "title": "P01 G02 Deep Quality Gauntlet",
      "description": "Aipo — P01 G02 Deep Quality Gauntlet",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P02-G01-wave3-types-and-values/",
      "slug": "P02-G01-wave3-types-and-values",
      "category": "development",
      "title": "P02 G01 Wave3 Types And Values",
      "description": "Aipo — P02 G01 Wave3 Types And Values",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P02-G02-wave3-stdlib-async/",
      "slug": "P02-G02-wave3-stdlib-async",
      "category": "development",
      "title": "P02 G02 Wave3 Stdlib Async",
      "description": "Aipo — P02 G02 Wave3 Stdlib Async",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P02-G03-wave3-async-syntax-and-diagnostics/",
      "slug": "P02-G03-wave3-async-syntax-and-diagnostics",
      "category": "development",
      "title": "P02 G03 Wave3 Async Syntax And Diagnostics",
      "description": "Aipo — P02 G03 Wave3 Async Syntax And Diagnostics",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P03-G01-host-abi/",
      "slug": "P03-G01-host-abi",
      "category": "development",
      "title": "P03 G01 Host Abi",
      "description": "Aipo — P03 G01 Host Abi",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/P03-G02-poppy-adapter-and-headless-demo/",
      "slug": "P03-G02-poppy-adapter-and-headless-demo",
      "category": "development",
      "title": "P03 G02 Poppy Adapter And Headless Demo",
      "description": "Aipo — P03 G02 Poppy Adapter And Headless Demo",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/conformance/",
      "slug": "conformance",
      "category": "development",
      "title": "Conformance",
      "description": "Aipo — Conformance",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/cross-language/",
      "slug": "cross-language",
      "category": "development",
      "title": "Cross Language",
      "description": "Aipo — Cross Language",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/performance-lessons/",
      "slug": "performance-lessons",
      "category": "development",
      "title": "Performance Lessons",
      "description": "Aipo — Performance Lessons",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/evidence/slices/",
      "slug": "slices",
      "category": "development",
      "title": "Slices",
      "description": "Aipo — Slices",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/governance/changelog/",
      "slug": "changelog",
      "category": "development",
      "title": "Changelog",
      "description": "Aipo — Changelog",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/governance/prumo-and-lpc/",
      "slug": "prumo-and-lpc",
      "category": "development",
      "title": "Prumo And Lpc",
      "description": "Aipo — Prumo And Lpc",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/governance/repository-governance/",
      "slug": "repository-governance",
      "category": "development",
      "title": "Repository Governance",
      "description": "Aipo — Repository Governance",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/governance/security-and-threat-model/",
      "slug": "security-and-threat-model",
      "category": "development",
      "title": "Security And Threat Model",
      "description": "Aipo — Security And Threat Model",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/governance/standards-and-testing/",
      "slug": "standards-and-testing",
      "category": "development",
      "title": "Standards And Testing",
      "description": "Aipo — Standards And Testing",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/performance/baseline/",
      "slug": "baseline",
      "category": "development",
      "title": "Baseline",
      "description": "Aipo — Baseline",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/performance/cross-language/",
      "slug": "cross-language",
      "category": "development",
      "title": "Cross Language",
      "description": "Aipo — Cross Language",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/zoe/components/advanced/",
      "slug": "advanced",
      "category": "development",
      "title": "Advanced",
      "description": "Aipo — Advanced",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/zoe/components/buttons/",
      "slug": "buttons",
      "category": "development",
      "title": "Buttons",
      "description": "Aipo — Buttons",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/zoe/components/inputs/",
      "slug": "inputs",
      "category": "development",
      "title": "Inputs",
      "description": "Aipo — Inputs",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/zoe/components/layout/",
      "slug": "layout",
      "category": "development",
      "title": "Layout",
      "description": "Aipo — Layout",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/zoe/components/navigation/",
      "slug": "navigation",
      "category": "development",
      "title": "Navigation",
      "description": "Aipo — Navigation",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/zoe/guide/custom-components/",
      "slug": "custom-components",
      "category": "development",
      "title": "Custom Components",
      "description": "Aipo — Custom Components",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/zoe/guide/getting-started/",
      "slug": "getting-started",
      "category": "development",
      "title": "Getting Started",
      "description": "Aipo — Getting Started",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/zoe/guide/layout-leona/",
      "slug": "layout-leona",
      "category": "development",
      "title": "Layout Leona",
      "description": "Aipo — Layout Leona",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/zoe/guide/reactivity/",
      "slug": "reactivity",
      "category": "development",
      "title": "Reactivity",
      "description": "Aipo — Reactivity",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/development/zoe/playground/",
      "slug": "playground",
      "category": "development",
      "title": "Playground",
      "description": "Aipo — Playground",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/getting-started/cli-overview/",
      "slug": "cli-overview",
      "category": "guides",
      "title": "Cli Overview",
      "description": "Aipo — Cli Overview",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/getting-started/first-program/",
      "slug": "first-program",
      "category": "guides",
      "title": "First Program",
      "description": "Aipo — First Program",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/getting-started/installation/",
      "slug": "installation",
      "category": "guides",
      "title": "Installation",
      "description": "Aipo — Installation",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/getting-started/what-is-aipo/",
      "slug": "what-is-aipo",
      "category": "guides",
      "title": "What Is Aipo",
      "description": "Aipo — What Is Aipo",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/manual/async-and-concurrency/",
      "slug": "async-and-concurrency",
      "category": "guides",
      "title": "Async And Concurrency",
      "description": "Aipo — Async And Concurrency",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/manual/control-flow/",
      "slug": "control-flow",
      "category": "guides",
      "title": "Control Flow",
      "description": "Aipo — Control Flow",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/manual/functions-and-closures/",
      "slug": "functions-and-closures",
      "category": "guides",
      "title": "Functions And Closures",
      "description": "Aipo — Functions And Closures",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/manual/interfaces-and-contracts/",
      "slug": "interfaces-and-contracts",
      "category": "guides",
      "title": "Interfaces And Contracts",
      "description": "Aipo — Interfaces And Contracts",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/manual/packages-and-modules/",
      "slug": "packages-and-modules",
      "category": "guides",
      "title": "Packages And Modules",
      "description": "Aipo — Packages And Modules",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/manual/stdlib/",
      "slug": "stdlib",
      "category": "guides",
      "title": "Stdlib",
      "description": "Aipo — Stdlib",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/manual/syntax-and-types/",
      "slug": "syntax-and-types",
      "category": "guides",
      "title": "Syntax And Types",
      "description": "Aipo — Syntax And Types",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/packages/aipo-game/",
      "slug": "aipo-game",
      "category": "guides",
      "title": "Aipo Game",
      "description": "Aipo — Aipo Game",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/packages/aipo-html/",
      "slug": "aipo-html",
      "category": "guides",
      "title": "Aipo Html",
      "description": "Aipo — Aipo Html",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/packages/aipo-http/",
      "slug": "aipo-http",
      "category": "guides",
      "title": "Aipo Http",
      "description": "Aipo — Aipo Http",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/packages/aipo-ui/",
      "slug": "aipo-ui",
      "category": "guides",
      "title": "Aipo Ui",
      "description": "Aipo — Aipo Ui",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/packages/aipo-zoe/",
      "slug": "aipo-zoe",
      "category": "guides",
      "title": "Aipo Zoe",
      "description": "Aipo — Aipo Zoe",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/trajectory/wave-0-mvp/",
      "slug": "wave-0-mvp",
      "category": "guides",
      "title": "Wave 0 Mvp",
      "description": "Aipo — Wave 0 Mvp",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/trajectory/wave-1-contracts/",
      "slug": "wave-1-contracts",
      "category": "guides",
      "title": "Wave 1 Contracts",
      "description": "Aipo — Wave 1 Contracts",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/trajectory/wave-2-js-parity/",
      "slug": "wave-2-js-parity",
      "category": "guides",
      "title": "Wave 2 Js Parity",
      "description": "Aipo — Wave 2 Js Parity",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/trajectory/wave-3-async/",
      "slug": "wave-3-async",
      "category": "guides",
      "title": "Wave 3 Async",
      "description": "Aipo — Wave 3 Async",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/trajectory/wave-4-host-poppy/",
      "slug": "wave-4-host-poppy",
      "category": "guides",
      "title": "Wave 4 Host Poppy",
      "description": "Aipo — Wave 4 Host Poppy",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/trajectory/wave-5-packages/",
      "slug": "wave-5-packages",
      "category": "guides",
      "title": "Wave 5 Packages",
      "description": "Aipo — Wave 5 Packages",
      "locale": "pt-BR"
    },
    {
      "route": "/aipo/docs/guides/trajectory/wave-6-release-v010/",
      "slug": "wave-6-release-v010",
      "category": "guides",
      "title": "Wave 6 Release V010",
      "description": "Aipo — Wave 6 Release V010",
      "locale": "pt-BR"
    },
    {
      "route": "/en/aipo/docs/development/adp/ADP-001-byte-and-core-types-as-values/",
      "slug": "ADP-001-byte-and-core-types-as-values",
      "category": "development",
      "title": "ADP 001 Byte And Core Types As Values",
      "description": "Aipo — ADP 001 Byte And Core Types As Values",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/adp/ADP-002-construction-hooks-and-runtime-contracts/",
      "slug": "ADP-002-construction-hooks-and-runtime-contracts",
      "category": "development",
      "title": "ADP 002 Construction Hooks And Runtime Contracts",
      "description": "Aipo — ADP 002 Construction Hooks And Runtime Contracts",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/adp/ADP-003-execution-budgets/",
      "slug": "ADP-003-execution-budgets",
      "category": "development",
      "title": "ADP 003 Execution Budgets",
      "description": "Aipo — ADP 003 Execution Budgets",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/adp/ADP-004-unicode-identifier-policy/",
      "slug": "ADP-004-unicode-identifier-policy",
      "category": "development",
      "title": "ADP 004 Unicode Identifier Policy",
      "description": "Aipo — ADP 004 Unicode Identifier Policy",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/adp/ADP-005-parser-recursion-bounds/",
      "slug": "ADP-005-parser-recursion-bounds",
      "category": "development",
      "title": "ADP 005 Parser Recursion Bounds",
      "description": "Aipo — ADP 005 Parser Recursion Bounds",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/adp/ADP-006-wave3-wave4-open-decisions/",
      "slug": "ADP-006-wave3-wave4-open-decisions",
      "category": "development",
      "title": "ADP 006 Wave3 Wave4 Open Decisions",
      "description": "Aipo — ADP 006 Wave3 Wave4 Open Decisions",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/adp/ADP-007-package-identity-and-distribution/",
      "slug": "ADP-007-package-identity-and-distribution",
      "category": "development",
      "title": "ADP 007 Package Identity And Distribution",
      "description": "Aipo — ADP 007 Package Identity And Distribution",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/adp/ADP-008-v0.1.0-language-release/",
      "slug": "ADP-008-v0.1.0-language-release",
      "category": "development",
      "title": "ADP 008 V0.1.0 Language Release",
      "description": "Aipo — ADP 008 V0.1.0 Language Release",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/adp/ADP-009-synchronous-c-abi/",
      "slug": "ADP-009-synchronous-c-abi",
      "category": "development",
      "title": "ADP 009 Synchronous C Abi",
      "description": "Aipo — ADP 009 Synchronous C Abi",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/adp/ADP-010-interoperability-thin-proofs/",
      "slug": "ADP-010-interoperability-thin-proofs",
      "category": "development",
      "title": "ADP 010 Interoperability Thin Proofs",
      "description": "Aipo — ADP 010 Interoperability Thin Proofs",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/adp/ADP-011-performance-and-ergonomics-roadmap/",
      "slug": "ADP-011-performance-and-ergonomics-roadmap",
      "category": "development",
      "title": "ADP 011 Performance And Ergonomics Roadmap",
      "description": "Aipo — ADP 011 Performance And Ergonomics Roadmap",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/architecture/adr/001-architecture-baseline/",
      "slug": "001-architecture-baseline",
      "category": "development",
      "title": "001 Architecture Baseline",
      "description": "Aipo — 001 Architecture Baseline",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/architecture/bytecode-and-vm/",
      "slug": "bytecode-and-vm",
      "category": "development",
      "title": "Bytecode And Vm",
      "description": "Aipo — Bytecode And Vm",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/architecture/clean-code-contract/",
      "slug": "clean-code-contract",
      "category": "development",
      "title": "Clean Code Contract",
      "description": "Aipo — Clean Code Contract",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/architecture/compiler-frontend/",
      "slug": "compiler-frontend",
      "category": "development",
      "title": "Compiler Frontend",
      "description": "Aipo — Compiler Frontend",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/architecture/crates/",
      "slug": "crates",
      "category": "development",
      "title": "Crates",
      "description": "Aipo — Crates",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/architecture/host-abi/",
      "slug": "host-abi",
      "category": "development",
      "title": "Host Abi",
      "description": "Aipo — Host Abi",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/architecture/js-emitter/",
      "slug": "js-emitter",
      "category": "development",
      "title": "Js Emitter",
      "description": "Aipo — Js Emitter",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/architecture/overview/",
      "slug": "overview",
      "category": "development",
      "title": "Overview",
      "description": "Aipo — Overview",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-001/",
      "slug": "adp-001",
      "category": "development",
      "title": "Adp 001",
      "description": "Aipo — Adp 001",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-002/",
      "slug": "adp-002",
      "category": "development",
      "title": "Adp 002",
      "description": "Aipo — Adp 002",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-003/",
      "slug": "adp-003",
      "category": "development",
      "title": "Adp 003",
      "description": "Aipo — Adp 003",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-004/",
      "slug": "adp-004",
      "category": "development",
      "title": "Adp 004",
      "description": "Aipo — Adp 004",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-005/",
      "slug": "adp-005",
      "category": "development",
      "title": "Adp 005",
      "description": "Aipo — Adp 005",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-006/",
      "slug": "adp-006",
      "category": "development",
      "title": "Adp 006",
      "description": "Aipo — Adp 006",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-007/",
      "slug": "adp-007",
      "category": "development",
      "title": "Adp 007",
      "description": "Aipo — Adp 007",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-008/",
      "slug": "adp-008",
      "category": "development",
      "title": "Adp 008",
      "description": "Aipo — Adp 008",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-009/",
      "slug": "adp-009",
      "category": "development",
      "title": "Adp 009",
      "description": "Aipo — Adp 009",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-010/",
      "slug": "adp-010",
      "category": "development",
      "title": "Adp 010",
      "description": "Aipo — Adp 010",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-011/",
      "slug": "adp-011",
      "category": "development",
      "title": "Adp 011",
      "description": "Aipo — Adp 011",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-012/",
      "slug": "adp-012",
      "category": "development",
      "title": "Adp 012",
      "description": "Aipo — Adp 012",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/decisions/adp-013/",
      "slug": "adp-013",
      "category": "development",
      "title": "Adp 013",
      "description": "Aipo — Adp 013",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/design/zoe-visual-modernization-dossier/",
      "slug": "zoe-visual-modernization-dossier",
      "category": "development",
      "title": "Zoe Visual Modernization Dossier",
      "description": "Aipo — Zoe Visual Modernization Dossier",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P00-G09-slice-s9/",
      "slug": "P00-G09-slice-s9",
      "category": "development",
      "title": "P00 G09 Slice S9",
      "description": "Aipo — P00 G09 Slice S9",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P00-G10-backend-completion/",
      "slug": "P00-G10-backend-completion",
      "category": "development",
      "title": "P00 G10 Backend Completion",
      "description": "Aipo — P00 G10 Backend Completion",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P00-G11-cli-and-formatter/",
      "slug": "P00-G11-cli-and-formatter",
      "category": "development",
      "title": "P00 G11 Cli And Formatter",
      "description": "Aipo — P00 G11 Cli And Formatter",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P00-G12-conformance-and-mvp-gate/",
      "slug": "P00-G12-conformance-and-mvp-gate",
      "category": "development",
      "title": "P00 G12 Conformance And Mvp Gate",
      "description": "Aipo — P00 G12 Conformance And Mvp Gate",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P00-G13-construction-hooks-and-bytes/",
      "slug": "P00-G13-construction-hooks-and-bytes",
      "category": "development",
      "title": "P00 G13 Construction Hooks And Bytes",
      "description": "Aipo — P00 G13 Construction Hooks And Bytes",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P00-G14-runtime-contract-enforcement/",
      "slug": "P00-G14-runtime-contract-enforcement",
      "category": "development",
      "title": "P00 G14 Runtime Contract Enforcement",
      "description": "Aipo — P00 G14 Runtime Contract Enforcement",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P00-G15-static-contracts-and-interface-conformance/",
      "slug": "P00-G15-static-contracts-and-interface-conformance",
      "category": "development",
      "title": "P00 G15 Static Contracts And Interface Conformance",
      "description": "Aipo — P00 G15 Static Contracts And Interface Conformance",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P00-G16-wave-1-exit-review/",
      "slug": "P00-G16-wave-1-exit-review",
      "category": "development",
      "title": "P00 G16 Wave 1 Exit Review",
      "description": "Aipo — P00 G16 Wave 1 Exit Review",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P01-G01-js-parity-mvp-subset/",
      "slug": "P01-G01-js-parity-mvp-subset",
      "category": "development",
      "title": "P01 G01 Js Parity Mvp Subset",
      "description": "Aipo — P01 G01 Js Parity Mvp Subset",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P01-G02-deep-quality-gauntlet/",
      "slug": "P01-G02-deep-quality-gauntlet",
      "category": "development",
      "title": "P01 G02 Deep Quality Gauntlet",
      "description": "Aipo — P01 G02 Deep Quality Gauntlet",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P02-G01-wave3-types-and-values/",
      "slug": "P02-G01-wave3-types-and-values",
      "category": "development",
      "title": "P02 G01 Wave3 Types And Values",
      "description": "Aipo — P02 G01 Wave3 Types And Values",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P02-G02-wave3-stdlib-async/",
      "slug": "P02-G02-wave3-stdlib-async",
      "category": "development",
      "title": "P02 G02 Wave3 Stdlib Async",
      "description": "Aipo — P02 G02 Wave3 Stdlib Async",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P02-G03-wave3-async-syntax-and-diagnostics/",
      "slug": "P02-G03-wave3-async-syntax-and-diagnostics",
      "category": "development",
      "title": "P02 G03 Wave3 Async Syntax And Diagnostics",
      "description": "Aipo — P02 G03 Wave3 Async Syntax And Diagnostics",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P03-G01-host-abi/",
      "slug": "P03-G01-host-abi",
      "category": "development",
      "title": "P03 G01 Host Abi",
      "description": "Aipo — P03 G01 Host Abi",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/P03-G02-poppy-adapter-and-headless-demo/",
      "slug": "P03-G02-poppy-adapter-and-headless-demo",
      "category": "development",
      "title": "P03 G02 Poppy Adapter And Headless Demo",
      "description": "Aipo — P03 G02 Poppy Adapter And Headless Demo",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/conformance/",
      "slug": "conformance",
      "category": "development",
      "title": "Conformance",
      "description": "Aipo — Conformance",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/cross-language/",
      "slug": "cross-language",
      "category": "development",
      "title": "Cross Language",
      "description": "Aipo — Cross Language",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/performance-lessons/",
      "slug": "performance-lessons",
      "category": "development",
      "title": "Performance Lessons",
      "description": "Aipo — Performance Lessons",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/evidence/slices/",
      "slug": "slices",
      "category": "development",
      "title": "Slices",
      "description": "Aipo — Slices",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/governance/changelog/",
      "slug": "changelog",
      "category": "development",
      "title": "Changelog",
      "description": "Aipo — Changelog",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/governance/prumo-and-lpc/",
      "slug": "prumo-and-lpc",
      "category": "development",
      "title": "Prumo And Lpc",
      "description": "Aipo — Prumo And Lpc",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/governance/repository-governance/",
      "slug": "repository-governance",
      "category": "development",
      "title": "Repository Governance",
      "description": "Aipo — Repository Governance",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/governance/security-and-threat-model/",
      "slug": "security-and-threat-model",
      "category": "development",
      "title": "Security And Threat Model",
      "description": "Aipo — Security And Threat Model",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/governance/standards-and-testing/",
      "slug": "standards-and-testing",
      "category": "development",
      "title": "Standards And Testing",
      "description": "Aipo — Standards And Testing",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/performance/baseline/",
      "slug": "baseline",
      "category": "development",
      "title": "Baseline",
      "description": "Aipo — Baseline",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/performance/cross-language/",
      "slug": "cross-language",
      "category": "development",
      "title": "Cross Language",
      "description": "Aipo — Cross Language",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/zoe/components/advanced/",
      "slug": "advanced",
      "category": "development",
      "title": "Advanced",
      "description": "Aipo — Advanced",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/zoe/components/buttons/",
      "slug": "buttons",
      "category": "development",
      "title": "Buttons",
      "description": "Aipo — Buttons",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/zoe/components/inputs/",
      "slug": "inputs",
      "category": "development",
      "title": "Inputs",
      "description": "Aipo — Inputs",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/zoe/components/layout/",
      "slug": "layout",
      "category": "development",
      "title": "Layout",
      "description": "Aipo — Layout",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/zoe/components/navigation/",
      "slug": "navigation",
      "category": "development",
      "title": "Navigation",
      "description": "Aipo — Navigation",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/zoe/guide/custom-components/",
      "slug": "custom-components",
      "category": "development",
      "title": "Custom Components",
      "description": "Aipo — Custom Components",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/zoe/guide/getting-started/",
      "slug": "getting-started",
      "category": "development",
      "title": "Getting Started",
      "description": "Aipo — Getting Started",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/zoe/guide/layout-leona/",
      "slug": "layout-leona",
      "category": "development",
      "title": "Layout Leona",
      "description": "Aipo — Layout Leona",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/zoe/guide/reactivity/",
      "slug": "reactivity",
      "category": "development",
      "title": "Reactivity",
      "description": "Aipo — Reactivity",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/development/zoe/playground/",
      "slug": "playground",
      "category": "development",
      "title": "Playground",
      "description": "Aipo — Playground",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/getting-started/cli-overview/",
      "slug": "cli-overview",
      "category": "guides",
      "title": "Cli Overview",
      "description": "Aipo — Cli Overview",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/getting-started/first-program/",
      "slug": "first-program",
      "category": "guides",
      "title": "First Program",
      "description": "Aipo — First Program",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/getting-started/installation/",
      "slug": "installation",
      "category": "guides",
      "title": "Installation",
      "description": "Aipo — Installation",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/getting-started/what-is-aipo/",
      "slug": "what-is-aipo",
      "category": "guides",
      "title": "What Is Aipo",
      "description": "Aipo — What Is Aipo",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/manual/async-and-concurrency/",
      "slug": "async-and-concurrency",
      "category": "guides",
      "title": "Async And Concurrency",
      "description": "Aipo — Async And Concurrency",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/manual/control-flow/",
      "slug": "control-flow",
      "category": "guides",
      "title": "Control Flow",
      "description": "Aipo — Control Flow",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/manual/functions-and-closures/",
      "slug": "functions-and-closures",
      "category": "guides",
      "title": "Functions And Closures",
      "description": "Aipo — Functions And Closures",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/manual/interfaces-and-contracts/",
      "slug": "interfaces-and-contracts",
      "category": "guides",
      "title": "Interfaces And Contracts",
      "description": "Aipo — Interfaces And Contracts",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/manual/packages-and-modules/",
      "slug": "packages-and-modules",
      "category": "guides",
      "title": "Packages And Modules",
      "description": "Aipo — Packages And Modules",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/manual/stdlib/",
      "slug": "stdlib",
      "category": "guides",
      "title": "Stdlib",
      "description": "Aipo — Stdlib",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/manual/syntax-and-types/",
      "slug": "syntax-and-types",
      "category": "guides",
      "title": "Syntax And Types",
      "description": "Aipo — Syntax And Types",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/packages/aipo-game/",
      "slug": "aipo-game",
      "category": "guides",
      "title": "Aipo Game",
      "description": "Aipo — Aipo Game",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/packages/aipo-html/",
      "slug": "aipo-html",
      "category": "guides",
      "title": "Aipo Html",
      "description": "Aipo — Aipo Html",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/packages/aipo-http/",
      "slug": "aipo-http",
      "category": "guides",
      "title": "Aipo Http",
      "description": "Aipo — Aipo Http",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/packages/aipo-ui/",
      "slug": "aipo-ui",
      "category": "guides",
      "title": "Aipo Ui",
      "description": "Aipo — Aipo Ui",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/packages/aipo-zoe/",
      "slug": "aipo-zoe",
      "category": "guides",
      "title": "Aipo Zoe",
      "description": "Aipo — Aipo Zoe",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/trajectory/wave-0-mvp/",
      "slug": "wave-0-mvp",
      "category": "guides",
      "title": "Wave 0 Mvp",
      "description": "Aipo — Wave 0 Mvp",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/trajectory/wave-1-contracts/",
      "slug": "wave-1-contracts",
      "category": "guides",
      "title": "Wave 1 Contracts",
      "description": "Aipo — Wave 1 Contracts",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/trajectory/wave-2-js-parity/",
      "slug": "wave-2-js-parity",
      "category": "guides",
      "title": "Wave 2 Js Parity",
      "description": "Aipo — Wave 2 Js Parity",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/trajectory/wave-3-async/",
      "slug": "wave-3-async",
      "category": "guides",
      "title": "Wave 3 Async",
      "description": "Aipo — Wave 3 Async",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/trajectory/wave-4-host-poppy/",
      "slug": "wave-4-host-poppy",
      "category": "guides",
      "title": "Wave 4 Host Poppy",
      "description": "Aipo — Wave 4 Host Poppy",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/trajectory/wave-5-packages/",
      "slug": "wave-5-packages",
      "category": "guides",
      "title": "Wave 5 Packages",
      "description": "Aipo — Wave 5 Packages",
      "locale": "en"
    },
    {
      "route": "/en/aipo/docs/guides/trajectory/wave-6-release-v010/",
      "slug": "wave-6-release-v010",
      "category": "guides",
      "title": "Wave 6 Release V010",
      "description": "Aipo — Wave 6 Release V010",
      "locale": "en"
    }
  ],
  "oride": [
    {
      "route": "/oride/docs/development/keymap/",
      "slug": "keymap",
      "category": "development",
      "title": "Mapa de teclas",
      "description": "Atalhos padrão e como remapeá-los.",
      "locale": "pt-BR"
    },
    {
      "route": "/oride/docs/development/layout/",
      "slug": "layout",
      "category": "development",
      "title": "Layout",
      "description": "Como a superfície do editor se organiza em painéis.",
      "locale": "pt-BR"
    },
    {
      "route": "/oride/docs/guides/config/",
      "slug": "config",
      "category": "guides",
      "title": "Configuração",
      "description": "Opções do editor, temas e preferências por projeto.",
      "locale": "pt-BR"
    },
    {
      "route": "/oride/docs/guides/markdown/",
      "slug": "markdown",
      "category": "guides",
      "title": "Markdown",
      "description": "Suporte a Markdown dentro do editor.",
      "locale": "pt-BR"
    },
    {
      "route": "/oride/docs/guides/syntax/",
      "slug": "syntax",
      "category": "guides",
      "title": "Sintaxe",
      "description": "A linguagem de edição usada nos arquivos do projeto.",
      "locale": "pt-BR"
    },
    {
      "route": "/oride/docs/guides/themes/",
      "slug": "themes",
      "category": "guides",
      "title": "Temas",
      "description": "Como o editor recebe cores e como definir um tema próprio.",
      "locale": "pt-BR"
    },
    {
      "route": "/oride/docs/guides/user-guide/",
      "slug": "user-guide",
      "category": "guides",
      "title": "Guia de uso",
      "description": "Os recursos do editor de terminal, da árvore de projeto à edição modal.",
      "locale": "pt-BR"
    },
    {
      "route": "/en/oride/docs/development/keymap/",
      "slug": "keymap",
      "category": "development",
      "title": "Key map",
      "description": "Default shortcuts and how to remap them.",
      "locale": "en"
    },
    {
      "route": "/en/oride/docs/development/layout/",
      "slug": "layout",
      "category": "development",
      "title": "Layout",
      "description": "How the editor surface is organised into panels.",
      "locale": "en"
    },
    {
      "route": "/en/oride/docs/guides/config/",
      "slug": "config",
      "category": "guides",
      "title": "Configuration",
      "description": "Editor options, themes, and per-project preferences.",
      "locale": "en"
    },
    {
      "route": "/en/oride/docs/guides/markdown/",
      "slug": "markdown",
      "category": "guides",
      "title": "Markdown",
      "description": "Markdown support inside the editor.",
      "locale": "en"
    },
    {
      "route": "/en/oride/docs/guides/syntax/",
      "slug": "syntax",
      "category": "guides",
      "title": "Syntax",
      "description": "The editing language used across the project’s files.",
      "locale": "en"
    },
    {
      "route": "/en/oride/docs/guides/themes/",
      "slug": "themes",
      "category": "guides",
      "title": "Themes",
      "description": "How the editor receives colors and how to define a custom theme.",
      "locale": "en"
    },
    {
      "route": "/en/oride/docs/guides/user-guide/",
      "slug": "user-guide",
      "category": "guides",
      "title": "User guide",
      "description": "The terminal editor’s features, from the project tree to modal editing.",
      "locale": "en"
    }
  ],
  "prumo": [
    {
      "route": "/prumo/docs/development/CONTRIBUTING/",
      "slug": "CONTRIBUTING",
      "category": "development",
      "title": "CONTRIBUTING",
      "description": "Prumo — CONTRIBUTING",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/architecture/dependency-rules/",
      "slug": "dependency-rules",
      "category": "development",
      "title": "Dependency Rules",
      "description": "Prumo — Dependency Rules",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/architecture/overview/",
      "slug": "overview",
      "category": "development",
      "title": "Overview",
      "description": "Prumo — Overview",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/architecture/viewer/",
      "slug": "viewer",
      "category": "development",
      "title": "Viewer",
      "description": "Prumo — Viewer",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/governance/authority/",
      "slug": "authority",
      "category": "development",
      "title": "Authority",
      "description": "Prumo — Authority",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/governance/lpc/",
      "slug": "lpc",
      "category": "development",
      "title": "Lpc",
      "description": "Prumo — Lpc",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/governance/m10-exit-gate/",
      "slug": "m10-exit-gate",
      "category": "development",
      "title": "M10 Exit Gate",
      "description": "Prumo — M10 Exit Gate",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/governance/m11-exit-gate/",
      "slug": "m11-exit-gate",
      "category": "development",
      "title": "M11 Exit Gate",
      "description": "Prumo — M11 Exit Gate",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/governance/m12-exit-gate/",
      "slug": "m12-exit-gate",
      "category": "development",
      "title": "M12 Exit Gate",
      "description": "Prumo — M12 Exit Gate",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/governance/m5-exit-gate/",
      "slug": "m5-exit-gate",
      "category": "development",
      "title": "M5 Exit Gate",
      "description": "Prumo — M5 Exit Gate",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/governance/m6-exit-gate/",
      "slug": "m6-exit-gate",
      "category": "development",
      "title": "M6 Exit Gate",
      "description": "Prumo — M6 Exit Gate",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/governance/m7-exit-gate/",
      "slug": "m7-exit-gate",
      "category": "development",
      "title": "M7 Exit Gate",
      "description": "Prumo — M7 Exit Gate",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/governance/m8-exit-gate/",
      "slug": "m8-exit-gate",
      "category": "development",
      "title": "M8 Exit Gate",
      "description": "Prumo — M8 Exit Gate",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/governance/m9-exit-gate/",
      "slug": "m9-exit-gate",
      "category": "development",
      "title": "M9 Exit Gate",
      "description": "Prumo — M9 Exit Gate",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/governance/trust-model/",
      "slug": "trust-model",
      "category": "development",
      "title": "Trust Model",
      "description": "Prumo — Trust Model",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/harness/aci-tools/",
      "slug": "aci-tools",
      "category": "development",
      "title": "Aci Tools",
      "description": "Prumo — Aci Tools",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/harness/directives/",
      "slug": "directives",
      "category": "development",
      "title": "Directives",
      "description": "Prumo — Directives",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/workforce/agents/",
      "slug": "agents",
      "category": "development",
      "title": "Agents",
      "description": "Prumo — Agents",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/workforce/recipes/",
      "slug": "recipes",
      "category": "development",
      "title": "Recipes",
      "description": "Prumo — Recipes",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/development/workforce/skills/",
      "slug": "skills",
      "category": "development",
      "title": "Skills",
      "description": "Prumo — Skills",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/guides/getting-started/adoption/",
      "slug": "adoption",
      "category": "guides",
      "title": "Adoption",
      "description": "Prumo — Adoption",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/guides/getting-started/concepts/",
      "slug": "concepts",
      "category": "guides",
      "title": "Concepts",
      "description": "Prumo — Concepts",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/guides/getting-started/first-project/",
      "slug": "first-project",
      "category": "guides",
      "title": "First Project",
      "description": "Prumo — First Project",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/guides/getting-started/installation/",
      "slug": "installation",
      "category": "guides",
      "title": "Installation",
      "description": "Prumo — Installation",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/guides/manual/connectors/",
      "slug": "connectors",
      "category": "guides",
      "title": "Connectors",
      "description": "Prumo — Connectors",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/guides/manual/installation/",
      "slug": "installation",
      "category": "guides",
      "title": "Installation",
      "description": "Prumo — Installation",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/guides/manual/uninstallation/",
      "slug": "uninstallation",
      "category": "guides",
      "title": "Uninstallation",
      "description": "Prumo — Uninstallation",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/guides/manual/usage/",
      "slug": "usage",
      "category": "guides",
      "title": "Usage",
      "description": "Prumo — Usage",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/guides/tools/cli-reference/",
      "slug": "cli-reference",
      "category": "guides",
      "title": "Cli Reference",
      "description": "Prumo — Cli Reference",
      "locale": "pt-BR"
    },
    {
      "route": "/prumo/docs/guides/tools/doctor/",
      "slug": "doctor",
      "category": "guides",
      "title": "Doctor",
      "description": "Prumo — Doctor",
      "locale": "pt-BR"
    },
    {
      "route": "/en/prumo/docs/development/CONTRIBUTING/",
      "slug": "CONTRIBUTING",
      "category": "development",
      "title": "CONTRIBUTING",
      "description": "Prumo — CONTRIBUTING",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/architecture/dependency-rules/",
      "slug": "dependency-rules",
      "category": "development",
      "title": "Dependency Rules",
      "description": "Prumo — Dependency Rules",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/architecture/overview/",
      "slug": "overview",
      "category": "development",
      "title": "Overview",
      "description": "Prumo — Overview",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/architecture/viewer/",
      "slug": "viewer",
      "category": "development",
      "title": "Viewer",
      "description": "Prumo — Viewer",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/governance/authority/",
      "slug": "authority",
      "category": "development",
      "title": "Authority",
      "description": "Prumo — Authority",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/governance/lpc/",
      "slug": "lpc",
      "category": "development",
      "title": "Lpc",
      "description": "Prumo — Lpc",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/governance/m10-exit-gate/",
      "slug": "m10-exit-gate",
      "category": "development",
      "title": "M10 Exit Gate",
      "description": "Prumo — M10 Exit Gate",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/governance/m11-exit-gate/",
      "slug": "m11-exit-gate",
      "category": "development",
      "title": "M11 Exit Gate",
      "description": "Prumo — M11 Exit Gate",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/governance/m12-exit-gate/",
      "slug": "m12-exit-gate",
      "category": "development",
      "title": "M12 Exit Gate",
      "description": "Prumo — M12 Exit Gate",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/governance/m5-exit-gate/",
      "slug": "m5-exit-gate",
      "category": "development",
      "title": "M5 Exit Gate",
      "description": "Prumo — M5 Exit Gate",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/governance/m6-exit-gate/",
      "slug": "m6-exit-gate",
      "category": "development",
      "title": "M6 Exit Gate",
      "description": "Prumo — M6 Exit Gate",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/governance/m7-exit-gate/",
      "slug": "m7-exit-gate",
      "category": "development",
      "title": "M7 Exit Gate",
      "description": "Prumo — M7 Exit Gate",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/governance/m8-exit-gate/",
      "slug": "m8-exit-gate",
      "category": "development",
      "title": "M8 Exit Gate",
      "description": "Prumo — M8 Exit Gate",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/governance/m9-exit-gate/",
      "slug": "m9-exit-gate",
      "category": "development",
      "title": "M9 Exit Gate",
      "description": "Prumo — M9 Exit Gate",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/governance/trust-model/",
      "slug": "trust-model",
      "category": "development",
      "title": "Trust Model",
      "description": "Prumo — Trust Model",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/harness/aci-tools/",
      "slug": "aci-tools",
      "category": "development",
      "title": "Aci Tools",
      "description": "Prumo — Aci Tools",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/harness/directives/",
      "slug": "directives",
      "category": "development",
      "title": "Directives",
      "description": "Prumo — Directives",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/workforce/agents/",
      "slug": "agents",
      "category": "development",
      "title": "Agents",
      "description": "Prumo — Agents",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/workforce/recipes/",
      "slug": "recipes",
      "category": "development",
      "title": "Recipes",
      "description": "Prumo — Recipes",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/development/workforce/skills/",
      "slug": "skills",
      "category": "development",
      "title": "Skills",
      "description": "Prumo — Skills",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/guides/getting-started/adoption/",
      "slug": "adoption",
      "category": "guides",
      "title": "Adoption",
      "description": "Prumo — Adoption",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/guides/getting-started/concepts/",
      "slug": "concepts",
      "category": "guides",
      "title": "Concepts",
      "description": "Prumo — Concepts",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/guides/getting-started/first-project/",
      "slug": "first-project",
      "category": "guides",
      "title": "First Project",
      "description": "Prumo — First Project",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/guides/getting-started/installation/",
      "slug": "installation",
      "category": "guides",
      "title": "Installation",
      "description": "Prumo — Installation",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/guides/manual/connectors/",
      "slug": "connectors",
      "category": "guides",
      "title": "Connectors",
      "description": "Prumo — Connectors",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/guides/manual/installation/",
      "slug": "installation",
      "category": "guides",
      "title": "Installation",
      "description": "Prumo — Installation",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/guides/manual/uninstallation/",
      "slug": "uninstallation",
      "category": "guides",
      "title": "Uninstallation",
      "description": "Prumo — Uninstallation",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/guides/manual/usage/",
      "slug": "usage",
      "category": "guides",
      "title": "Usage",
      "description": "Prumo — Usage",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/guides/tools/cli-reference/",
      "slug": "cli-reference",
      "category": "guides",
      "title": "Cli Reference",
      "description": "Prumo — Cli Reference",
      "locale": "en"
    },
    {
      "route": "/en/prumo/docs/guides/tools/doctor/",
      "slug": "doctor",
      "category": "guides",
      "title": "Doctor",
      "description": "Prumo — Doctor",
      "locale": "en"
    }
  ]
};
